### ISSUE TITLE
AzureDevOpsDsc: Built module contain folder 'Examples'

### ISSUE THREAD

**Issue by johlju** [dsccommunity/AzureDevOpsDsc#11]
We should remove the entry `Examples` from here:

https://github.com/dsccommunity/AzureDevOpsDsc/blob/8d43d12989359b8facdf46d86011a34dfe787898/build.yaml#L5-L9

Examples should be avoided to pass in the built module to minimize the size of the package that is distributed. Examples should be added automatically into the resource conceptual help. 

_DscResource.DocGenerator has as build task for this `Generate_Conceptual_Help` but should be learned how to generate conceptual help for class-based resources if it only know how to do it for MOF-based resource._

**Comment by SphenicPaul** [comment]
I've added [issue #51](https://github.com/dsccommunity/DscResource.DocGenerator/issues/51) in `DscResource.DocGenerator` project.

I'm trying to close this issue (within PR #28) with just the removal of the `Examples` directory but I'll update #15 to ensure "Examples" are included in that issue and add a reference to the above, `DscResource.DocGenerator` issue.
